# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  default: &default
  adapter: postgresql
  encoding: unicode
  database: new_datinglibre_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: new_datinglibre_test
  host: localhost
  # pool: 5
  username: postgres
  password: postgres

